### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jlottosen**
Added 3 maps of the wild:
- Making a Map of Risks
- Mapping Test strategies, on the community forum
- Mapping Low Code, on the community forum

### CODE REVIEW

**Comment by juliusgb** [comment]
Hi @jlottosen 

I think the article 'Broaden Scope of SUT' would fit here better than the others because it's more broad and looks at testing not only the components/system under test but also where they're running (cloud, data centre, etc) and the emerging test practices that come with it.

I'm using the heuristic from https://github.com/sindresorhus/awesome/blob/main/awesome.md

**Comment by jlottosen** [comment]
Hi Julius and all,

I wasn't aware of that heuristic for the curation. Please add it to the contribution guide.
 
Do add either "mapping test strategies" or "broad the scope of SUT", thank you.

I'm puzzled wrt the other two, though. Mapping of risks and low code are separate topics (and not so much on testing). 
The low code was discussed on the forum, that's why I link to that one specifically.
The risk one, is a novel way to use maps to understand the landscape, why is that different to blogging, losing your phone etc?

**Comment by juliusgb** [comment]
The curation part will be added in Issue #19 

On "Map of Risk":

- I thought it was incomplete because the last sentence is incomplete.
- the rows of 'Elaboration' already exit in the stages table (see "understanding")
- I see risk as a combination of likelihood ("understanding") and consequences of it happening (see "failure")

Evolution-Cheatsheet-Risk

Then there's a few threads on risks with maps:

- One of them (https://twitter.com/madplatt/status/1273182338462240770?s=20) + corresponding blog series (https://medium.com/@marioplatt/quantitative-risk-management-with-fair-stage-1-ransomware-scenario-d2e3a9d49b60) -> 
- Another: https://twitter.com/MatthewEGunter/status/1275469036319580160?s=20

The forum contains much more than what ends up on this list.

**Comment by jlottosen** [comment]
all right. close this PR, I'll make a new wrt test strategies.

**Comment by juliusgb** [comment]
No problem. Please keep up the writing - it's useful, even though it doesn't end up on this list. I'm in the same boat - not all posts end up here :)

**Pull request closed without merging**
